"use client";

import { useActionState, useMemo, useState } from "react";
import { PackagePlus, Plus, Truck, X } from "lucide-react";
import { createPurchase, createSupplier, receivePurchase, type PurchaseState } from "@/app/dashboard/purchases/actions";

type Supplier = { id: string; name: string };
type Product = { id: string; name: string; sku: string; cost: number };
export type PurchaseItem = { id: string; productName: string; quantityPieces: number; receivedPieces: number; unitCost: number };
type DraftLine = { product_id: string; quantity_pieces: number; unit_cost: number };
const initial: PurchaseState = {};
const money = (value: number) => new Intl.NumberFormat("en-PH", { style: "currency", currency: "PHP" }).format(value);

export function SupplierForm() {
  const [open, setOpen] = useState(false);
  const [state, action, pending] = useActionState(createSupplier, initial);
  return <><button className="btn-secondary" onClick={() => setOpen(true)} type="button"><Plus size={15} />Supplier</button>{open && <Modal title="Add supplier" close={() => setOpen(false)}><form action={action}><div className="grid gap-4 sm:grid-cols-2"><Field label="Supplier name" name="name" required /><Field label="Contact person" name="contactName" /><Field label="Phone" name="phone" /><Field label="Email" name="email" type="email" /><label className="text-xs font-bold sm:col-span-2"><span className="mb-1.5 block">Address</span><textarea className="field min-h-20 text-sm" name="address" /></label></div>{state.error && <ErrorMessage text={state.error} />}<div className="mt-5 flex justify-end"><button className="btn-primary" disabled={pending}>{pending ? "Saving…" : "Add supplier"}</button></div></form></Modal>}</>;
}

export function PurchaseOrderForm({ suppliers, products }: { suppliers: Supplier[]; products: Product[] }) {
  const [open, setOpen] = useState(false);
  const [lines, setLines] = useState<DraftLine[]>([]);
  const [selected, setSelected] = useState(products[0]?.id ?? "");
  const [state, action, pending] = useActionState(createPurchase, initial);
  const total = lines.reduce((sum, line) => sum + line.quantity_pieces * line.unit_cost, 0);
  function addLine() { const product = products.find((item) => item.id === selected); if (!product || lines.some((line) => line.product_id === product.id)) return; setLines((current) => [...current, { product_id: product.id, quantity_pieces: 1, unit_cost: product.cost }]); }
  return <><button className="btn-primary" disabled={!suppliers.length || !products.length} onClick={() => setOpen(true)} type="button"><PackagePlus size={16} />New purchase order</button>{open && <Modal title="New purchase order" close={() => setOpen(false)} wide><form action={action}><div className="grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold"><span className="mb-1.5 block">Supplier</span><select className="field text-sm" name="supplierId" required><option value="">Choose supplier</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.name}</option>)}</select></label><Field label="Supplier reference" name="supplierReference" /></div><div className="mt-5 flex gap-2"><select className="field text-sm" value={selected} onChange={(event) => setSelected(event.target.value)}>{products.map((product) => <option key={product.id} value={product.id}>{product.name} · {product.sku}</option>)}</select><button className="btn-secondary shrink-0" onClick={addLine} type="button"><Plus size={15} />Add</button></div><input name="items" type="hidden" value={JSON.stringify(lines)} /><div className="mt-4 space-y-2">{lines.map((line) => { const product = products.find((item) => item.id === line.product_id)!; return <div className="grid items-end gap-2 rounded-xl border border-[#e3e8e5] p-3 sm:grid-cols-[1fr_120px_140px_90px]" key={line.product_id}><div><p className="text-sm font-extrabold">{product.name}</p><p className="text-[10px] text-[#89948e]">Ordered in individual pieces</p></div><Field label="Pieces" name={`qty-${line.product_id}`} type="number" value={line.quantity_pieces} onChange={(value) => setLines((current) => current.map((item) => item.product_id === line.product_id ? { ...item, quantity_pieces: Math.max(1, Number(value) || 1) } : item))} /><Field label="Cost / piece" name={`cost-${line.product_id}`} type="number" value={line.unit_cost} onChange={(value) => setLines((current) => current.map((item) => item.product_id === line.product_id ? { ...item, unit_cost: Math.max(0, Number(value) || 0) } : item))} /><button className="btn-secondary py-2 text-xs" onClick={() => setLines((current) => current.filter((item) => item.product_id !== line.product_id))} type="button">Remove</button></div>; })}{!lines.length && <p className="rounded-xl bg-[#f5f8f6] py-8 text-center text-xs text-[#849088]">Add products to the purchase order.</p>}</div><label className="mt-4 block text-xs font-bold"><span className="mb-1.5 block">Notes</span><textarea className="field min-h-16 text-sm" name="notes" /></label>{state.error && <ErrorMessage text={state.error} />}<div className="mt-5 flex items-center justify-between"><div><p className="text-[10px] font-bold text-[#87928c]">ORDER TOTAL</p><p className="text-xl font-black">{money(total)}</p></div><button className="btn-primary" disabled={pending || !lines.length}>{pending ? "Creating…" : "Create order"}</button></div></form></Modal>}</>;
}

export function ReceivePurchaseButton({ purchaseOrderId, items }: { purchaseOrderId: string; items: PurchaseItem[] }) {
  const [open, setOpen] = useState(false);
  const [quantities, setQuantities] = useState<Record<string, number>>({});
  const [state, action, pending] = useActionState(receivePurchase, initial);
  const payload = useMemo(() => items.map((item) => ({ purchase_order_item_id: item.id, quantity_pieces: quantities[item.id] ?? 0 })).filter((item) => item.quantity_pieces > 0), [items, quantities]);
  return <><button className="btn-secondary py-2 text-xs" onClick={() => setOpen(true)} type="button"><Truck size={14} />Receive</button>{open && <Modal title="Receive inventory" close={() => setOpen(false)}><form action={action}><input name="purchaseOrderId" type="hidden" value={purchaseOrderId} /><input name="items" type="hidden" value={JSON.stringify(payload)} /><div className="space-y-3">{items.map((item) => { const remaining = item.quantityPieces - item.receivedPieces; return <label className="flex items-center gap-3 rounded-xl border border-[#e3e8e5] p-3" key={item.id}><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{item.productName}</p><p className="text-xs text-[#849088]">{remaining} pieces remaining · {money(item.unitCost)} each</p></div><input className="field w-24 text-center text-sm" max={remaining} min="0" type="number" value={quantities[item.id] ?? 0} onChange={(event) => setQuantities((current) => ({ ...current, [item.id]: Math.max(0, Math.min(remaining, Number(event.target.value) || 0)) }))} /></label>; })}</div>{state.error && <ErrorMessage text={state.error} />}{state.success && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm font-semibold text-emerald-700">{state.success}</p>}<div className="mt-5 flex justify-end"><button className="btn-primary" disabled={pending || !payload.length}>{pending ? "Receiving…" : "Confirm received stock"}</button></div></form></Modal>}</>;
}

function Modal({ title, close, wide, children }: { title: string; close: () => void; wide?: boolean; children: React.ReactNode }) { return <div className="fixed inset-0 z-50 grid place-items-center overflow-y-auto bg-[#10251c]/50 p-4 backdrop-blur-sm"><div className={`my-5 w-full rounded-2xl bg-white shadow-2xl ${wide ? "max-w-3xl" : "max-w-lg"}`}><div className="flex items-center justify-between border-b border-[#e6ebe8] px-6 py-5"><h2 className="text-xl font-black">{title}</h2><button className="grid h-9 w-9 place-items-center rounded-lg hover:bg-[#f1f4f2]" onClick={close} type="button"><X size={18} /></button></div><div className="max-h-[75vh] overflow-y-auto p-6">{children}</div></div></div>; }
function ErrorMessage({ text }: { text: string }) { return <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-semibold text-red-700">{text}</p>; }
function Field({ label, name, type = "text", required, value, onChange }: { label: string; name: string; type?: string; required?: boolean; value?: number; onChange?: (value: string) => void }) { return <label className="text-xs font-bold"><span className="mb-1.5 block">{label}</span><input className="field text-sm" name={name} type={type} required={required} min={type === "number" ? 0 : undefined} step={type === "number" ? "0.01" : undefined} value={value} onChange={onChange ? (event) => onChange(event.target.value) : undefined} /></label>; }
